import test from 'node:test';
import assert from 'node:assert/strict';
import {calculateCover} from '../src/batch-features.mjs';

// Generated by solution-finder 1.42 `spin --split yes`, then checked with
// `cover -K jstris180.properties -d 180`. These exercise the operation-history
// Fumen representation used by legacy T-spin cover workflows.
const MINI_TSS_HISTORY='v115@RhA8LeG8JeRLYVAFLDmClcJSAVDEHBEooRBJoAVB0AAAAvhA1uB';
const REGULAR_TSS_HISTORY='v115@vhExPYYAFLDmClcJSAVDEHBEooRBJoAVBs/9tCSyB+pBdsBXrB';

test('operation-history T-spin Mini target matches SFinder TSM/TSS oracle', async()=>{
  const tsm=await calculateCover({sourceFumen:MINI_TSS_HISTORY,pattern:'TI',clear:4,mode:'tsm',mirror:'no'});
  const tss=await calculateCover({sourceFumen:MINI_TSS_HISTORY,pattern:'TI',clear:4,mode:'tss',mirror:'no'});
  assert.equal(tsm.covered,1);assert.equal(tsm.total,1);assert.equal(tsm.failed,0);
  assert.equal(tss.covered,0);assert.equal(tss.total,1);assert.equal(tss.failed,1);
});

test('operation-history regular TSS target matches SFinder cover oracle', async()=>{
  for(const [mode,expected] of [['normal',1],['tsm',1],['tss',1],['tsd',0],['tst',0]]){
    const r=await calculateCover({sourceFumen:REGULAR_TSS_HISTORY,pattern:'JILST',clear:4,mode,mirror:'no',useHold:false});
    assert.equal(r.covered,expected,mode);assert.equal(r.total,1,mode);
  }
});

const REGULAR_TSD_I_TUCK_HISTORY='v115@vhFRPYZAFLDmClcJSAVDEHBEooRBJoAVBsuntC6AAA?AipBlrB+tB3sBsqB';

test('operation-history TSD preserves SFinder Jstris I-CCW tuck reachability', async()=>{
  const r=await calculateCover({
    sourceFumen:REGULAR_TSD_I_TUCK_HISTORY,
    pattern:'*p6',
    clear:4,
    mode:'tsd',
    mirror:'no',
  });
  assert.equal(r.total,5040);
  assert.equal(r.covered,312);
  assert.equal(r.failed,4728);
});

// Continuous two-page Regular TST history. The upper two rows are physical
// blockers required by the Jstris rotation path; truncating the history to the
// requested 4-line target height changes reachability and incorrectly rejects
// this target. Cross-checked with solution-finder 1.42 cover: 1/1 in tst mode.
const REGULAR_TST_SIX_ROW_HISTORY='v115@qgB8CeA8BeC8DeF8AeI8BeH8EeC8BeA8AeD8LeRLJv?hANlB';

test('operation-history TST preserves upper-row blockers and matches SFinder oracle', async()=>{
  for(const [mode,expected] of [['normal',1],['tsm',1],['tss',1],['tsd',1],['tst',1]]){
    const r=await calculateCover({
      sourceFumen:REGULAR_TST_SIX_ROW_HISTORY,
      pattern:'IT',
      clear:4,
      mode,
      mirror:'no',
      useHold:false,
    });
    assert.equal(r.total,1,mode);
    assert.equal(r.covered,expected,mode);
  }
});
