import test from'node:test';import assert from'node:assert/strict';import{decoder}from'tetris-fumen';import{createWasmSolver}from'../src/wasm-backend.mjs';import{calculateSaves,calculateMinimalsFeature,calculateLegacyMinimalsFeature}from'../src/features.mjs';
const B='v115@9gglIeglHewwhlzhBexwzhEewwJeAgH',P='T,[^TIL]!,*p2';
test('ezsaves T 1008/1008 with dual queue contract',async()=>{const s=await createWasmSolver(4);try{const r=calculateSaves({sourceFumen:B,pattern:P,wantedSave:'T',solver:s});assert.equal(r.pathPattern,'T,[JSZO]!,*p2');assert.equal(r.analysisPattern,P);assert.deepEqual([r.success,r.total],[1008,1008]);assert.equal(r.failedQueues.length,0)}finally{s.close()}});
test('ezminimals T keeps exact cardinality and coverage while representative geometry may differ',async()=>{const s=await createWasmSolver(4);try{const r=await calculateMinimalsFeature({sourceFumen:B,pattern:P,wantedSave:'T',solver:s});assert.equal(r.minimalCount,7);assert.deepEqual(r.coverageCounts,[288,288,288,288,288,192,144]);const pages=decoder.decode(r.fumen);assert.equal(pages.length,7);assert.deepEqual(pages.map(p=>p.comment),[...Array(5).fill('28.57% (288/1008)'),'19.05% (192/1008)','14.29% (144/1008)'])}finally{s.close()}});

test('minimals API is adaptive async while legacy minimals stays synchronous',async()=>{const s=await createWasmSolver(4);try{const pending=calculateMinimalsFeature({sourceFumen:B,pattern:P,wantedSave:'T',solver:s});assert.equal(typeof pending?.then,'function');const current=await pending;const legacy=calculateLegacyMinimalsFeature({sourceFumen:B,pattern:P,wantedSave:'T',solver:s});assert.equal(current.minimalCount,legacy.minimalCount);assert.deepEqual(current.coverageCounts,legacy.coverageCounts);assert.equal(current.humanQualityExact,true)}finally{s.close()}});

test('minimals ALL is the same as an omitted save filter',async()=>{const s=await createWasmSolver(4);try{const omitted=await calculateMinimalsFeature({sourceFumen:B,pattern:P,wantedSave:'',solver:s,useHiGHS:false});const all=await calculateMinimalsFeature({sourceFumen:B,pattern:P,wantedSave:'ALL',solver:s,useHiGHS:false});assert.equal(all.saveSuccess,omitted.saveSuccess);assert.equal(all.minimalCount,omitted.minimalCount);assert.deepEqual(all.coverageCounts,omitted.coverageCounts);const legacyOmitted=calculateLegacyMinimalsFeature({sourceFumen:B,pattern:P,wantedSave:'',solver:s});const legacyAll=calculateLegacyMinimalsFeature({sourceFumen:B,pattern:P,wantedSave:'ALL',solver:s});assert.equal(legacyAll.saveSuccess,legacyOmitted.saveSuccess);assert.equal(legacyAll.minimalCount,legacyOmitted.minimalCount);assert.deepEqual(legacyAll.coverageCounts,legacyOmitted.coverageCounts)}finally{s.close()}});

test('minimals preserves exact save multiplicity for TT and regex',async()=>{const s=await createWasmSolver(4);try{const expectedCoverage=[24,16,16,16,16,16,12,12,12,12,8];for(const wantedSave of ['TT','/TT/']){const current=await calculateMinimalsFeature({sourceFumen:B,pattern:P,wantedSave,solver:s,useHiGHS:false});assert.equal(current.saveSuccess,152);assert.equal(current.minimalCount,11);assert.deepEqual(current.coverageCounts,expectedCoverage);const legacy=calculateLegacyMinimalsFeature({sourceFumen:B,pattern:P,wantedSave,solver:s});assert.equal(legacy.saveSuccess,152);assert.equal(legacy.minimalCount,11);assert.deepEqual(legacy.coverageCounts,expectedCoverage)}}finally{s.close()}});
